# Generated by Django 3.2.2 on 2021-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210516_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(verbose_name="Childs's age"),
        ),
        migrations.AlterField(
            model_name='application',
            name='f_name',
            field=models.CharField(max_length=20, verbose_name="Child's first name"),
        ),
        migrations.AlterField(
            model_name='application',
            name='l_name',
            field=models.CharField(max_length=30, verbose_name="Child's last name"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
