# Generated by Django 3.2.2 on 2021-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210516_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='parent_tel_numb',
            field=models.CharField(max_length=10, verbose_name="Parent's telephone number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_tel_numb',
            field=models.CharField(max_length=10, verbose_name="Parent's telephone number"),
        ),
    ]
